--------------------------------------------------------
--  파일이 생성됨 - 수요일-11월-30-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ADDITIONAL
--------------------------------------------------------

  CREATE TABLE "CSHYEONJU"."ADDITIONAL" 
   (	"NO" VARCHAR2(20 BYTE), 
	"BIRTH" DATE, 
	"TYPE" VARCHAR2(20 BYTE), 
	"WORKINGHOUR" NUMBER, 
	"VACATIONHOUR" NUMBER, 
	"ENTRY" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ANNUALSTATUS
--------------------------------------------------------

  CREATE TABLE "CSHYEONJU"."ANNUALSTATUS" 
   (	"EMPNO" VARCHAR2(20 BYTE), 
	"YEAR" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"TOTAL" VARCHAR2(20 BYTE), 
	"LEFTOVER" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ATTENDANCE
--------------------------------------------------------

  CREATE TABLE "CSHYEONJU"."ATTENDANCE" 
   (	"EMPNO" VARCHAR2(20 BYTE), 
	"ATNDDATE" DATE, 
	"ATNDTYPE" VARCHAR2(20 BYTE), 
	"STARTTIME" VARCHAR2(20 BYTE), 
	"STOPTIME" VARCHAR2(20 BYTE), 
	"NOTE" VARCHAR2(1024 BYTE), 
	"CONFIRM" VARCHAR2(20 BYTE), 
	"CONFIRMUSER" VARCHAR2(20 BYTE), 
	"CONFIRMDATE" DATE, 
	"TIME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COMPANY
--------------------------------------------------------

  CREATE TABLE "CSHYEONJU"."COMPANY" 
   (	"CNAME" VARCHAR2(20 BYTE), 
	"FOUNDING" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DEPT
--------------------------------------------------------

  CREATE TABLE "CSHYEONJU"."DEPT" 
   (	"CODE" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(20 BYTE), 
	"COMPANY" VARCHAR2(20 BYTE), 
	"HEAD" VARCHAR2(20 BYTE), 
	"LOCATION" VARCHAR2(20 BYTE), 
	"SENIORDEPT" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMP
--------------------------------------------------------

  CREATE TABLE "CSHYEONJU"."EMP" 
   (	"NO" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(20 BYTE), 
	"DEPT" VARCHAR2(20 BYTE), 
	"RANK" VARCHAR2(20 BYTE), 
	"TEL" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(40 BYTE), 
	"STATUS" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table WORKSTATUS
--------------------------------------------------------

  CREATE TABLE "CSHYEONJU"."WORKSTATUS" 
   (	"EMPNO" VARCHAR2(20 BYTE), 
	"MONTH" VARCHAR2(20 BYTE), 
	"PLANTIME" NUMBER, 
	"CURRENTTIME" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into CSHYEONJU.ADDITIONAL
SET DEFINE OFF;
Insert into CSHYEONJU.ADDITIONAL (NO,BIRTH,TYPE,WORKINGHOUR,VACATIONHOUR,ENTRY) values ('2022001',to_date('00/05/30','RR/MM/DD'),'계약직',40,96,to_date('21/07/01','RR/MM/DD'));
REM INSERTING into CSHYEONJU.ANNUALSTATUS
SET DEFINE OFF;
Insert into CSHYEONJU.ANNUALSTATUS (EMPNO,YEAR,TYPE,TOTAL,LEFTOVER) values ('2022001','2022','연차','96','40');
Insert into CSHYEONJU.ANNUALSTATUS (EMPNO,YEAR,TYPE,TOTAL,LEFTOVER) values ('2022001','2022','대휴','24','24');
REM INSERTING into CSHYEONJU.ATTENDANCE
SET DEFINE OFF;
Insert into CSHYEONJU.ATTENDANCE (EMPNO,ATNDDATE,ATNDTYPE,STARTTIME,STOPTIME,NOTE,CONFIRM,CONFIRMUSER,CONFIRMDATE,TIME) values ('2022001',to_date('22/11/01','RR/MM/DD'),'출근','09:00','18:00',' ','승인','2022003',to_date('22/11/05','RR/MM/DD'),null);
Insert into CSHYEONJU.ATTENDANCE (EMPNO,ATNDDATE,ATNDTYPE,STARTTIME,STOPTIME,NOTE,CONFIRM,CONFIRMUSER,CONFIRMDATE,TIME) values ('2022001',to_date('22/11/02','RR/MM/DD'),'조퇴','09:00','15:00','병결조퇴','승인','2022003',to_date('22/11/05','RR/MM/DD'),null);
Insert into CSHYEONJU.ATTENDANCE (EMPNO,ATNDDATE,ATNDTYPE,STARTTIME,STOPTIME,NOTE,CONFIRM,CONFIRMUSER,CONFIRMDATE,TIME) values ('2022002',to_date('22/11/02','RR/MM/DD'),'결근',null,null,'무단결근','승인','2022003',to_date('22/11/05','RR/MM/DD'),null);
Insert into CSHYEONJU.ATTENDANCE (EMPNO,ATNDDATE,ATNDTYPE,STARTTIME,STOPTIME,NOTE,CONFIRM,CONFIRMUSER,CONFIRMDATE,TIME) values ('2022001',to_date('22/11/18','RR/MM/DD'),'휴가','09:00','13:00',null,null,null,null,null);
Insert into CSHYEONJU.ATTENDANCE (EMPNO,ATNDDATE,ATNDTYPE,STARTTIME,STOPTIME,NOTE,CONFIRM,CONFIRMUSER,CONFIRMDATE,TIME) values ('2022001',to_date('22/11/22','RR/MM/DD'),'퇴근','12:08:44','12:25:20',null,null,null,null,null);
Insert into CSHYEONJU.ATTENDANCE (EMPNO,ATNDDATE,ATNDTYPE,STARTTIME,STOPTIME,NOTE,CONFIRM,CONFIRMUSER,CONFIRMDATE,TIME) values ('2022001',to_date('22/11/30','RR/MM/DD'),'퇴근','11:15:02','11:15:25','지각한 사유',null,null,null,null);
REM INSERTING into CSHYEONJU.COMPANY
SET DEFINE OFF;
Insert into CSHYEONJU.COMPANY (CNAME,FOUNDING) values ('개발혁동조합',to_date('00/05/30','RR/MM/DD'));
REM INSERTING into CSHYEONJU.DEPT
SET DEFINE OFF;
Insert into CSHYEONJU.DEPT (CODE,NAME,COMPANY,HEAD,LOCATION,SENIORDEPT) values ('mk000','영업부','개발혁동조합','2022003','본사 2층',null);
Insert into CSHYEONJU.DEPT (CODE,NAME,COMPANY,HEAD,LOCATION,SENIORDEPT) values ('mk010','인천지점','개발혁동조합','2022001','인천시 남동구','mk000');
Insert into CSHYEONJU.DEPT (CODE,NAME,COMPANY,HEAD,LOCATION,SENIORDEPT) values ('mk011','부천지점','개발혁동조합',null,'경기도 부천시','mk000');
Insert into CSHYEONJU.DEPT (CODE,NAME,COMPANY,HEAD,LOCATION,SENIORDEPT) values ('mg000','경영지원부','개발혁동조합','2022001','본사 3층',null);
REM INSERTING into CSHYEONJU.EMP
SET DEFINE OFF;
Insert into CSHYEONJU.EMP (NO,PASSWORD,NAME,DEPT,RANK,TEL,EMAIL,STATUS) values ('2022001','qwe123','조현주','mk010','지점장','01046706407','0@gmail.com','재직');
Insert into CSHYEONJU.EMP (NO,PASSWORD,NAME,DEPT,RANK,TEL,EMAIL,STATUS) values ('2022002','pwd123','홍길동','mg000','부장','01012345678','gildong@naver.com','퇴사');
Insert into CSHYEONJU.EMP (NO,PASSWORD,NAME,DEPT,RANK,TEL,EMAIL,STATUS) values ('2022003','abc12','고길동','mk000','부장','01087654321','gogil@naver.com','재직');
REM INSERTING into CSHYEONJU.WORKSTATUS
SET DEFINE OFF;
Insert into CSHYEONJU.WORKSTATUS (EMPNO,MONTH,PLANTIME,CURRENTTIME) values ('2022001','2022/11',196,185);
--------------------------------------------------------
--  DDL for Index EMP_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CSHYEONJU"."EMP_PK" ON "CSHYEONJU"."EMP" ("NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index WORKSTATUS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CSHYEONJU"."WORKSTATUS_PK" ON "CSHYEONJU"."WORKSTATUS" ("EMPNO", "MONTH") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DEPT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CSHYEONJU"."DEPT_PK" ON "CSHYEONJU"."DEPT" ("CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index COMPANY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CSHYEONJU"."COMPANY_PK" ON "CSHYEONJU"."COMPANY" ("CNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ATTENDANCE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CSHYEONJU"."ATTENDANCE_PK" ON "CSHYEONJU"."ATTENDANCE" ("EMPNO", "ATNDDATE", "ATNDTYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ANNUALSTATUS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CSHYEONJU"."ANNUALSTATUS_PK" ON "CSHYEONJU"."ANNUALSTATUS" ("EMPNO", "YEAR", "TYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ADDITIONAL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CSHYEONJU"."ADDITIONAL_PK" ON "CSHYEONJU"."ADDITIONAL" ("NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table DEPT
--------------------------------------------------------

  ALTER TABLE "CSHYEONJU"."DEPT" ADD CONSTRAINT "DEPT_PK" PRIMARY KEY ("CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CSHYEONJU"."DEPT" MODIFY ("CODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMP
--------------------------------------------------------

  ALTER TABLE "CSHYEONJU"."EMP" ADD CONSTRAINT "EMP_PK" PRIMARY KEY ("NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CSHYEONJU"."EMP" MODIFY ("NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COMPANY
--------------------------------------------------------

  ALTER TABLE "CSHYEONJU"."COMPANY" ADD CONSTRAINT "COMPANY_PK" PRIMARY KEY ("CNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CSHYEONJU"."COMPANY" MODIFY ("CNAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ATTENDANCE
--------------------------------------------------------

  ALTER TABLE "CSHYEONJU"."ATTENDANCE" ADD CONSTRAINT "ATTENDANCE_PK" PRIMARY KEY ("EMPNO", "ATNDDATE", "ATNDTYPE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CSHYEONJU"."ATTENDANCE" MODIFY ("ATNDTYPE" NOT NULL ENABLE);
  ALTER TABLE "CSHYEONJU"."ATTENDANCE" MODIFY ("ATNDDATE" NOT NULL ENABLE);
  ALTER TABLE "CSHYEONJU"."ATTENDANCE" MODIFY ("EMPNO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ADDITIONAL
--------------------------------------------------------

  ALTER TABLE "CSHYEONJU"."ADDITIONAL" ADD CONSTRAINT "ADDITIONAL_PK" PRIMARY KEY ("NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CSHYEONJU"."ADDITIONAL" MODIFY ("NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ANNUALSTATUS
--------------------------------------------------------

  ALTER TABLE "CSHYEONJU"."ANNUALSTATUS" ADD CONSTRAINT "ANNUALSTATUS_PK" PRIMARY KEY ("EMPNO", "YEAR", "TYPE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CSHYEONJU"."ANNUALSTATUS" MODIFY ("EMPNO" NOT NULL ENABLE);
  ALTER TABLE "CSHYEONJU"."ANNUALSTATUS" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "CSHYEONJU"."ANNUALSTATUS" MODIFY ("YEAR" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table WORKSTATUS
--------------------------------------------------------

  ALTER TABLE "CSHYEONJU"."WORKSTATUS" ADD CONSTRAINT "WORKSTATUS_PK" PRIMARY KEY ("EMPNO", "MONTH")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CSHYEONJU"."WORKSTATUS" MODIFY ("MONTH" NOT NULL ENABLE);
  ALTER TABLE "CSHYEONJU"."WORKSTATUS" MODIFY ("EMPNO" NOT NULL ENABLE);
