--------------------------------------------------------
--  파일이 생성됨 - 수요일-12월-14-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DEPT
--------------------------------------------------------

  CREATE TABLE "CSHYEONJU"."DEPT" 
   (	"CODE" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(20 BYTE), 
	"COMPANY" VARCHAR2(20 BYTE), 
	"LOCATION" VARCHAR2(50 BYTE), 
	"SENIORDEPT" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into CSHYEONJU.DEPT
SET DEFINE OFF;
Insert into CSHYEONJU.DEPT (CODE,NAME,COMPANY,LOCATION,SENIORDEPT) values ('MK000','영업부','개발혁동조합','본사 2층',null);
Insert into CSHYEONJU.DEPT (CODE,NAME,COMPANY,LOCATION,SENIORDEPT) values ('MK010','인천지점','개발혁동조합','인천시 남동구','MK000');
Insert into CSHYEONJU.DEPT (CODE,NAME,COMPANY,LOCATION,SENIORDEPT) values ('MK011','부천지점','개발혁동조합','경기도 부천시','MK000');
Insert into CSHYEONJU.DEPT (CODE,NAME,COMPANY,LOCATION,SENIORDEPT) values ('BS000','경영지원부','개발혁동조합','본사 3층',null);
Insert into CSHYEONJU.DEPT (CODE,NAME,COMPANY,LOCATION,SENIORDEPT) values ('MK012','서울지점','개발혁동조합','서울특별시 강남구','MK000');
Insert into CSHYEONJU.DEPT (CODE,NAME,COMPANY,LOCATION,SENIORDEPT) values ('BS010','경리팀','개발혁동조합','본사 3층','BS000');
Insert into CSHYEONJU.DEPT (CODE,NAME,COMPANY,LOCATION,SENIORDEPT) values ('BS011','지원팀','개발혁동조합','본사 3층','BS000');
Insert into CSHYEONJU.DEPT (CODE,NAME,COMPANY,LOCATION,SENIORDEPT) values ('DEV000','개발부','개발혁동조합','본사 25층',null);
Insert into CSHYEONJU.DEPT (CODE,NAME,COMPANY,LOCATION,SENIORDEPT) values ('DEV010','시스템팀','개발혁동조합','본사 26층','DEV000');
Insert into CSHYEONJU.DEPT (CODE,NAME,COMPANY,LOCATION,SENIORDEPT) values ('DEV011','모바일팀','개발혁동조합','본사 26층','DEV000');
Insert into CSHYEONJU.DEPT (CODE,NAME,COMPANY,LOCATION,SENIORDEPT) values ('ES000','이사회','개발혁동조합','본사 30층',null);
--------------------------------------------------------
--  DDL for Index DEPT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CSHYEONJU"."DEPT_PK" ON "CSHYEONJU"."DEPT" ("CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table DEPT
--------------------------------------------------------

  ALTER TABLE "CSHYEONJU"."DEPT" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "CSHYEONJU"."DEPT" ADD CONSTRAINT "DEPT_PK" PRIMARY KEY ("CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DEPT
--------------------------------------------------------

  ALTER TABLE "CSHYEONJU"."DEPT" ADD CONSTRAINT "DEPT_COMPANY" FOREIGN KEY ("COMPANY")
	  REFERENCES "CSHYEONJU"."COMPANY" ("CNAME") ENABLE;
  ALTER TABLE "CSHYEONJU"."DEPT" ADD CONSTRAINT "DEPT_SENIORDEPT" FOREIGN KEY ("SENIORDEPT")
	  REFERENCES "CSHYEONJU"."DEPT" ("CODE") ENABLE;
